Repository no-types/RagGrid, pull requests merged in 2018-05, with the labels that each got.

#6 includings aggrid enterprice only if key is provided
  DESCRIPTION
  R/RagGrid.R
  inst/htmlwidgets/lib/aggrid-enterprice/aggridenterprise.min.js
Labels: enhancement

#13 column opts merging added closes #12
  R/RagGrid.R
  RagGrid.Rproj
  inst/htmlwidgets/RagGrid.js
  inst/htmlwidgets/RagGrid.js.map
  javascript/RagGrid.js
  man/aggrid.Rd
Labels: enhancement

#15 numeral formatting added closes #14
  R/RagGrid.R
  inst/htmlwidgets/RagGrid.js
  inst/htmlwidgets/RagGrid.js.map
  inst/htmlwidgets/RagGrid.yaml
  inst/htmlwidgets/lib/numeral/numeral.min.js
  javascript/RagGrid.js
  man/aggrid.Rd
Labels: enhancement

#17 Check for testing
  inst/examples/aggrid.R
Labels: in progress

#18 Add shiny example
  inst/examples/aggrid-shiny/server.R
  inst/examples/aggrid-shiny/ui.R
  inst/examples/aggrid.R
Labels: in progress

#22 import htmltools fix closes #20
  NAMESPACE
Labels: bug, in progress
